// Compatibility forwarder. Remove after all callers move to the Canvas feature boundary.
export {
  MAX_UPSCALE_LONG_EDGE,
  canvasAnglePrompt,
  imageCropRectFromDraft,
  imageToolDraftFromCropRect,
  moveImageCropRect,
  resizeImageCropRect,
  resolveUpscaleSize,
} from "@/features/canvas/domain/imageData";
export type {
  ImageAngleLensPreset,
  ImageAnglePromptDraft,
  ImageAngleTransform,
  ImageAngleViewPreset,
  ImageCompressionFormat,
  ImageCompressionParams,
  ImageCompressionResult,
  ImageCropBox,
  ImageCropDraft,
  ImageCropRect,
  ImageCropResizeHandle,
  ImageFlipDirection,
  ImageSplitParams,
  ImageSplitPiece,
  ImageUpscaleAlgorithm,
  ImageUpscaleParams,
  OutpaintMargins,
  StoryboardFrame,
  StoryboardLayout,
} from "@/features/canvas/domain/imageData";
export {
  composeStoryboardDataUrl,
  compressDataUrl,
  conformDataUrlToSize,
  createOutpaintMaskDataUrl,
  createOutpaintSourceDataUrl,
  cropDataUrl,
  flipDataUrl,
  splitDataUrl,
  transformAngleDataUrl,
  upscaleDataUrl,
} from "@/features/canvas/adapters/imageData";
