#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/nanoid@5.1.16/node_modules/nanoid/bin/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/nanoid@5.1.16/node_modules/nanoid/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/nanoid@5.1.16/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/nanoid@5.1.16/node_modules/nanoid/bin/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/nanoid@5.1.16/node_modules/nanoid/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/nanoid@5.1.16/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../nanoid/bin/nanoid.js" "$@"
else
  exec node  "$basedir/../nanoid/bin/nanoid.js" "$@"
fi
