#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/vite@7.3.6_@types+node@24.13.3_jiti@2.7.0_lightningcss@1.32.0_tsx@4.23.1/node_modules/vite/bin/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/vite@7.3.6_@types+node@24.13.3_jiti@2.7.0_lightningcss@1.32.0_tsx@4.23.1/node_modules/vite/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/vite@7.3.6_@types+node@24.13.3_jiti@2.7.0_lightningcss@1.32.0_tsx@4.23.1/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/node_modules"
else
  export NODE_PATH="/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/vite@7.3.6_@types+node@24.13.3_jiti@2.7.0_lightningcss@1.32.0_tsx@4.23.1/node_modules/vite/bin/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/vite@7.3.6_@types+node@24.13.3_jiti@2.7.0_lightningcss@1.32.0_tsx@4.23.1/node_modules/vite/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/vite@7.3.6_@types+node@24.13.3_jiti@2.7.0_lightningcss@1.32.0_tsx@4.23.1/node_modules:/mnt/d/ITEM/projects_no_local_deps_2026-07-01/cavans原型/ai-manju-project/.modules-studio-isolated/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../vite/bin/vite.js" "$@"
else
  exec node  "$basedir/../vite/bin/vite.js" "$@"
fi
