from __future__ import annotations

from dataclasses import dataclass
import hashlib
import math
import threading
import time
from typing import Any

from redis import Redis


WAITING_PROVIDER_PHASE = "waiting_provider_slot"
DEFAULT_PROVIDER_MAX_CONCURRENCY = 3
MIN_PROVIDER_MAX_CONCURRENCY = 1
MAX_PROVIDER_MAX_CONCURRENCY = 8


@dataclass(frozen=True)
class GateDecision:
    acquired: bool
    retry_after_seconds: int = 1


class ProviderGate:
    """Redis-backed fair semaphore shared by all worker replicas.

    Pending jobs are grouped by workspace and the workspace ring is rotated
    after each acquisition. The upstream credential is represented only by an
    HMAC generated by the API; this class hashes it again for Redis key safety.
    """

    _ACQUIRE_SCRIPT = """
local now_ms = tonumber(ARGV[1])
local lease_until = tonumber(ARGV[2])
local max_concurrency = tonumber(ARGV[3])
local workspace = ARGV[4]
local job_id = ARGV[5]
local ticket_ttl = tonumber(ARGV[6])

redis.call('ZREMRANGEBYSCORE', KEYS[1], '-inf', now_ms)

if redis.call('EXISTS', KEYS[4]) == 0 then
  local queue_was_empty = redis.call('LLEN', KEYS[3]) == 0
  redis.call('RPUSH', KEYS[3], job_id)
  redis.call('SET', KEYS[4], workspace, 'PX', ticket_ttl)
  if queue_was_empty then
    redis.call('RPUSH', KEYS[2], workspace)
  end
end

local cooldown_until = tonumber(redis.call('GET', KEYS[5]) or '0')
if cooldown_until > now_ms then
  return {0, math.max(250, cooldown_until - now_ms)}
end

if redis.call('ZCARD', KEYS[1]) >= max_concurrency then
  local earliest = redis.call('ZRANGE', KEYS[1], 0, 0, 'WITHSCORES')
  local wait_ms = 500
  if earliest[2] then
    wait_ms = math.max(250, math.min(1000, tonumber(earliest[2]) - now_ms))
  end
  return {0, wait_ms}
end

local turn = redis.call('LINDEX', KEYS[2], 0)
local last_workspace = redis.call('GET', KEYS[6])
if redis.call('LLEN', KEYS[2]) > 1 and turn == last_workspace then
  redis.call('LPOP', KEYS[2])
  redis.call('RPUSH', KEYS[2], turn)
  turn = redis.call('LINDEX', KEYS[2], 0)
end
if turn ~= workspace then
  return {0, 500}
end
if redis.call('LINDEX', KEYS[3], 0) ~= job_id then
  return {0, 500}
end

redis.call('LPOP', KEYS[3])
redis.call('LPOP', KEYS[2])
if redis.call('LLEN', KEYS[3]) > 0 then
  redis.call('RPUSH', KEYS[2], workspace)
else
  redis.call('DEL', KEYS[3])
end
redis.call('DEL', KEYS[4])
redis.call('ZADD', KEYS[1], lease_until, job_id)
redis.call('SET', KEYS[6], workspace)
return {1, lease_until}
"""

    _REMOVE_WAITER_SCRIPT = """
redis.call('LREM', KEYS[2], 0, ARGV[2])
redis.call('DEL', KEYS[3])
if redis.call('LLEN', KEYS[2]) == 0 then
  redis.call('DEL', KEYS[2])
  redis.call('LREM', KEYS[1], 0, ARGV[1])
end
return 1
"""

    def __init__(self, redis_url: str, gate_key: str, lease_seconds: int = 960, client: Any | None = None) -> None:
        digest = hashlib.sha256(gate_key.encode("utf-8")).hexdigest()
        self.prefix = f"ai-manju:provider-gate:{digest}"
        self.client = client or Redis.from_url(redis_url, decode_responses=True, socket_connect_timeout=2, socket_timeout=3)
        self.lease_seconds = max(30, int(lease_seconds))
        self._heartbeat_stop: threading.Event | None = None
        self._heartbeat_thread: threading.Thread | None = None

    def _workspace_key(self, workspace_id: str) -> str:
        digest = hashlib.sha256(workspace_id.encode("utf-8")).hexdigest()[:24]
        return f"{self.prefix}:workspace:{digest}:pending"

    def _ticket_key(self, job_id: str) -> str:
        digest = hashlib.sha256(job_id.encode("utf-8")).hexdigest()[:32]
        return f"{self.prefix}:ticket:{digest}"

    @property
    def active_key(self) -> str:
        return f"{self.prefix}:active"

    @property
    def ring_key(self) -> str:
        return f"{self.prefix}:workspace-ring"

    @property
    def cooldown_key(self) -> str:
        return f"{self.prefix}:cooldown-until"

    @property
    def last_workspace_key(self) -> str:
        return f"{self.prefix}:last-workspace"

    def acquire(self, workspace_id: str, job_id: str, max_concurrency: int) -> GateDecision:
        now_ms = int(time.time() * 1000)
        lease_until = now_ms + self.lease_seconds * 1000
        ticket_ttl = max(self.lease_seconds * 4, 3600) * 1000
        result = self.client.eval(
            self._ACQUIRE_SCRIPT,
            6,
            self.active_key,
            self.ring_key,
            self._workspace_key(workspace_id),
            self._ticket_key(job_id),
            self.cooldown_key,
            self.last_workspace_key,
            now_ms,
            lease_until,
            max(
                MIN_PROVIDER_MAX_CONCURRENCY,
                min(MAX_PROVIDER_MAX_CONCURRENCY, int(max_concurrency or DEFAULT_PROVIDER_MAX_CONCURRENCY)),
            ),
            workspace_id,
            job_id,
            ticket_ttl,
        )
        acquired = bool(int(result[0]))
        if acquired:
            return GateDecision(acquired=True)
        wait_ms = max(250, int(result[1] or 1000))
        return GateDecision(acquired=False, retry_after_seconds=max(1, math.ceil(wait_ms / 1000)))

    def remove_waiter(self, workspace_id: str, job_id: str) -> None:
        self.client.eval(
            self._REMOVE_WAITER_SCRIPT,
            3,
            self.ring_key,
            self._workspace_key(workspace_id),
            self._ticket_key(job_id),
            workspace_id,
            job_id,
        )

    def start_heartbeat(self, job_id: str) -> None:
        if self._heartbeat_thread is not None:
            return
        stop = threading.Event()
        self._heartbeat_stop = stop

        def run() -> None:
            interval = max(5, self.lease_seconds // 3)
            while not stop.wait(interval):
                try:
                    expires_at = int(time.time() * 1000) + self.lease_seconds * 1000
                    self.client.zadd(self.active_key, {job_id: expires_at}, xx=True)
                except Exception:
                    # Losing a heartbeat must not cancel an in-flight upstream
                    # request; the lease still has a conservative timeout.
                    continue

        self._heartbeat_thread = threading.Thread(target=run, name=f"provider-gate-{job_id}", daemon=True)
        self._heartbeat_thread.start()

    def set_cooldown(self, retry_after_seconds: int) -> None:
        retry_after_seconds = max(1, int(retry_after_seconds))
        until = int(time.time() * 1000) + retry_after_seconds * 1000
        # Keep the furthest observed cooldown when multiple workers receive 429.
        current = int(self.client.get(self.cooldown_key) or 0)
        if until > current:
            self.client.set(self.cooldown_key, until, px=retry_after_seconds * 1000)

    def release(self, job_id: str) -> None:
        if self._heartbeat_stop is not None:
            self._heartbeat_stop.set()
        if self._heartbeat_thread is not None:
            self._heartbeat_thread.join(timeout=1)
        self._heartbeat_stop = None
        self._heartbeat_thread = None
        self.client.zrem(self.active_key, job_id)


def provider_gate_from_payload(payload: dict[str, Any], redis_url: str, lease_seconds: int) -> tuple[ProviderGate, int] | None:
    provider = payload.get("provider")
    if not isinstance(provider, dict):
        return None
    gate_key = str(provider.get("gate_key") or "").strip()
    if not gate_key:
        return None
    limit = max(
        MIN_PROVIDER_MAX_CONCURRENCY,
        min(MAX_PROVIDER_MAX_CONCURRENCY, int(provider.get("max_concurrency") or DEFAULT_PROVIDER_MAX_CONCURRENCY)),
    )
    return ProviderGate(redis_url, gate_key, lease_seconds), limit
